name: Build and Release Exe
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyotp pwinput pywin32 psutil beautifulsoup4

    - name: Install PyInstaller (yt-dlp build)
      run: |
        pip install https://github.com/yt-dlp/Pyinstaller-Builds/releases/download/2026.05.02.225304/pyinstaller-6.20.0-py3-none-win_amd64.whl

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --icon=icon.ico launcher.py

    - name: Upload Exe to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/launcher.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
